<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWdqkha0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWdqkha0/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWdqkha0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWdqkha0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWdqkha0\appProdProjectContainer([
    'container.build_hash' => 'Wdqkha0',
    'container.build_id' => '7034ef7e',
    'container.build_time' => 1593554216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWdqkha0');
